services:
  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManager/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=TaskManagementDb;Username=postgres;Password=password123
    networks:
      - taskmanagement-network
    ports:
      - "8080:80"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: TaskManagementDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanagement-network

volumes:
  postgres_data:
networks:
  taskmanagement-network:
    driver: bridge  
